// Generated by https://quicktype.io

export interface SurveyResultResponse {
  survey_results: SurveyResult[];
}

export interface SurveyResult {
  name:                      string;
  url:                       string;
  participant_count:         string;
  response_rate:             number;
  submitted_response_count:  number;
  router_link?:              string;
}

export interface SurveyResultDetailResponse {
  survey_result_detail: SurveyResultDetail;
}

export interface SurveyResultDetail {
  name:                     string;
  url:                      string;
  participant_count:        number;
  response_rate:            number;
  submitted_response_count: number;
  themes:                   Theme[];
}

export interface Theme {
  name:      string;
  questions: Question[];
}

export interface Question {
  description:       string;
  question_type:     string;
  survey_responses:  SurveyResponse[];
  average_rating?:    number;
}

export interface SurveyResponse {
  id:                number;
  question_id:       number;
  respondent_id:     number;
  response_content:  string;
}
